name: "${project.name}"
version: "${project.version}"
website: "${project.parent.url}"
author: Agon KOLGECI

load: POSTWORLD
main: com.agonkolgeci.nexus.NexusAPIBootstrap

depend: [ LuckPerms, DecentHolograms ]