name: "${project.name}"
version: "${project.version}"
website: "${project.parent.url}"
author: Agon KOLGECI

load: POSTWORLD
api-version: 1.21
main: com.agonkolgeci.nexus.NexusAPIBootstrap

depend: [ LuckPerms ]